"""
Agent 5 – File Writer
Writes all converted Terraform files to the output directory.
Direction-aware: uses direction metadata in the README.
"""
from pathlib import Path

from src.graph.state import ConversionState
from src.directions import get_direction


def writer_agent(state: ConversionState) -> ConversionState:
    """LangGraph node: persist all converted content to disk."""
    output_dir = Path(state.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Write converted resource files ─────────────────────────────────
    for cf in state.converted_files:
        dest = Path(cf.output_path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        try:
            dest.write_text(cf.aws_content, encoding="utf-8")
        except Exception as exc:
            state.errors.append(f"Writer: could not write {dest} – {exc}")

    # ── Write supporting files (named for the target cloud) ───────────────
    direction = get_direction(state.direction)
    suffix = direction.output_suffix  # e.g. "_aws", "_gcp", "_azure"
    _write_if_content(output_dir / "provider.tf",                state.provider_tf)
    _write_if_content(output_dir / f"variables{suffix}.tf",      state.variables_tf)
    _write_if_content(output_dir / f"outputs{suffix}.tf",        state.outputs_tf)
    _write_if_content(output_dir / "backend.tf",                 state.backend_tf)

    # ── Write README ───────────────────────────────────────────────────
    _write_if_content(output_dir / "README.md", _build_readme(state))

    return state


def _write_if_content(path: Path, content: str) -> None:
    if content and content.strip():
        try:
            path.write_text(content, encoding="utf-8")
        except Exception:
            pass


def _build_readme(state: ConversionState) -> str:
    direction = get_direction(state.direction)
    total_converted = len(state.converted_files)
    total_failed = len(state.failed_files)
    all_resources = []
    for f in state.converted_files:
        all_resources.extend(f.resources_converted)
    unique_resources = sorted(set(all_resources))

    lines = [
        f"# {direction.source_label} → {direction.target_label} Terraform Migration",
        "",
        f"Auto-generated by **cloud-iac-converter** (LangGraph + LLM)  ",
        f"Direction: `{direction.key}`",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Direction | {direction.source_cloud} → {direction.target_cloud} |",
        f"| Source files processed | {state.total_files} |",
        f"| Files converted | {total_converted} |",
        f"| Files failed | {total_failed} |",
        f"| Target resource types | {len(unique_resources)} |",
        "",
    ]

    if unique_resources:
        lines += ["## Target Resources Generated", ""]
        for r in unique_resources:
            lines.append(f"- `{r}`")
        lines.append("")

    if state.conversion_plan:
        lines += ["## Conversion Plan", "", state.conversion_plan, ""]

    if state.warnings:
        lines += ["## ⚠️ Warnings", ""]
        for w in state.warnings:
            lines.append(f"- {w}")
        lines.append("")

    if state.failed_files:
        lines += ["## ❌ Failed Files", ""]
        for f in state.failed_files:
            lines.append(f"- {f}")
        lines.append("")

    lines += [
        "## Next Steps",
        "",
        "1. Review and update `variables.tf` with your actual values.",
        "2. Configure `backend.tf` for remote state.",
        "3. Run `terraform init`",
        "4. Run `terraform plan`",
        "5. Run `terraform apply`",
        "",
        "> **Note**: Always review generated IAM/RBAC policies for least-privilege compliance.",
        "",
    ]

    return "\n".join(lines)
